---
- name: clickhouse-htz-01
  resources:
    cpus: 2
    memory: 2048
  network:
  - ip: 172.200.1.101
  - ip: 172.200.2.101

- name: clickhouse-htz-02
  resources:
    cpus: 2
    memory: 2048
  network:
  - ip: 172.200.1.102
  - ip: 172.200.2.102

- name: clickhouse-htz-03
  resources:
    cpus: 2
    memory: 2048
  network:
  - ip: 172.200.1.103
  - ip: 172.200.2.103

- name: clickhouse-htz-04
  resources:
    cpus: 1
    memory: 1024
  network:
  - ip: 172.200.1.104
  - ip: 172.200.2.104

- name: clickhouse-htz-05
  resources:
    cpus: 1
    memory: 1024
  network:
  - ip: 172.200.1.105
  - ip: 172.200.2.105

- name: clickhouse-htz-06
  resources:
    cpus: 1
    memory: 1024
  network:
  - ip: 172.200.1.106
  - ip: 172.200.2.106
